name: ci
# specify the events this workflow should run on
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  # manual button click from the GitHub UI
  workflow_dispatch:
  # pushing commit to the main branch
  push:
    branches:
      - main
  # test site every night
  schedule:
      - cron: '0 4 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
